import { MoodType, MoodValue } from "@/types";
import { MOOD_COLORS } from "./moodColors";

export const MOODS: Record<MoodValue, MoodType> = {
  1: {
    value: 1,
    label: "Struggling",
    emoji: "😭",
    description: "Having a hard time",
    colorName: "struggling",
    bgLight: "bg-rose-50/80",
    bgDark: "bg-rose-950/20",
    borderLight: "border-rose-200/50",
    borderDark: "border-rose-900/40",
    textLight: "text-rose-700",
    textDark: "text-rose-300",
    hex: MOOD_COLORS[1].base,
  },
  2: {
    value: 2,
    label: "Low",
    emoji: "😔",
    description: "Feeling down or tired",
    colorName: "low",
    bgLight: "bg-orange-50/80",
    bgDark: "bg-orange-950/20",
    borderLight: "border-orange-200/50",
    borderDark: "border-orange-900/40",
    textLight: "text-orange-700",
    textDark: "text-orange-300",
    hex: MOOD_COLORS[2].base,
  },
  3: {
    value: 3,
    label: "Okay",
    emoji: "😐",
    description: "Neutral & balanced",
    colorName: "okay",
    bgLight: "bg-yellow-50/80",
    bgDark: "bg-yellow-950/20",
    borderLight: "border-yellow-200/50",
    borderDark: "border-yellow-900/40",
    textLight: "text-yellow-700",
    textDark: "text-yellow-300",
    hex: MOOD_COLORS[3].base,
  },
  4: {
    value: 4,
    label: "Good",
    emoji: "🙂",
    description: "Happy & content",
    colorName: "good",
    bgLight: "bg-emerald-50/80",
    bgDark: "bg-emerald-950/20",
    borderLight: "border-emerald-200/50",
    borderDark: "border-emerald-900/40",
    textLight: "text-emerald-700",
    textDark: "text-emerald-300",
    hex: MOOD_COLORS[4].base,
  },
  5: {
    value: 5,
    label: "Peaceful",
    emoji: "😌",
    description: "Calm & relaxed",
    colorName: "peaceful",
    bgLight: "bg-teal-50/80",
    bgDark: "bg-teal-950/20",
    borderLight: "border-teal-200/50",
    borderDark: "border-teal-900/40",
    textLight: "text-teal-700",
    textDark: "text-teal-300",
    hex: MOOD_COLORS[5].base,
  },
  6: {
    value: 6,
    label: "Great",
    emoji: "🤩",
    description: "Radiant & energized",
    colorName: "great",
    bgLight: "bg-amber-50/80",
    bgDark: "bg-amber-950/20",
    borderLight: "border-amber-200/50",
    borderDark: "border-amber-900/40",
    textLight: "text-amber-700",
    textDark: "text-amber-300",
    hex: MOOD_COLORS[6].base,
  },
};

/**
 * MOOD_LIST sorted ASCENDING by value (1 → 6).
 * This is the canonical render order: Struggling → Low → Okay → Good → Peaceful → Great
 */
export const MOOD_LIST = Object.values(MOODS).sort((a, b) => a.value - b.value);
